apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app_name: pyapp
  name: pyapp
spec:
  ports:
  - name: 1111-80
    nodePort: 30009
    port: 1112
    protocol: TCP
    targetPort: 80
  selector:
    app_name: pyapp
  type: NodePort
status:
  loadBalancer: {}
