apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testing
  name: testing
spec:
  ports:
  - nodePort: 30008
    port: 1111
    protocol: TCP
    targetPort: 80
  selector:
    run: testing
  type: NodePort
status:
  loadBalancer: {}
