apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testing-cluster
  name: testing-cluster
spec:
  ports:
  - port: 1111
    protocol: TCP
    targetPort: 80
  selector:
    run: testing
  type: ClusterIP
status:
  loadBalancer: {}
