apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testing-lb
  name: testing-lb
spec:
  ports:
  - port: 5678
    protocol: TCP
    targetPort: 80
  selector:
    app: testing
    run: testing
  type: LoadBalancer
